#include <iostream>
#include <string>
using namespace std;

void prnt(int i) {
	if (i < 0) {
		throw "Число i < 0"; // Выбрасывается массив типа char, но можно выбросить int и другой тип данных.
	}
	else if (i == 0) {
		throw exception("Число i = 0"); //Можно закомментить первую строку.
	}
	else if (i == 1) {
		throw 1;
	}
	cout << "Переменная i = " << i << endl;
}

int main() {
	setlocale(LC_ALL, "ru");
	try
	{
		prnt(1);
	}
	catch (char const* str) // Массив чаров передаётся как указатель на первый элемент
	{
		cout << "Поймана строка: " << str << endl;
	}
	catch (exception& ex) { // Второй catch нужен в том случае, если неизвестен тип исключения, который мы ловим
		cout << "Поймано исключение: " << ex.what() << endl;
	}
	catch (...) { // Так же, если тип исключения неизвестен, эта конструкция обрабатывает любой тип исключения
		cout << "Что-то пошло не так: " << endl; // Но эта конструкция может быть только в конце
	}

	//	Из-за того, что тип выбрасываемого исключения может быть любой, лучше использовать exception, как стандарт

	return 0;
}